cc_test(
    name = "celestial_body_test",
    size = "small",
    srcs = ["celestial_body_test.cpp"],
    deps = [
        "//src/eaps",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "kepler_problem_test",
    size = "small",
    srcs = ["kepler_problem_test.cpp"],
    deps = [
        "//src/eaps",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "vector3_test",
    size = "small",
    srcs = ["vector3_test.cpp"],
    deps = [
        "//src/eaps",
        "@com_google_googletest//:gtest_main",
    ],
)
