cc_library(
    name = "eaps",
    srcs = [
        "celestial_body.cpp",
        "kepler_problem.cpp",
        "vector3.cpp",
    ],
    hdrs = [
        "celestial_body.hpp",
        "config.hpp",
        "kepler_problem.hpp",
        "vector3.hpp",
    ],
    data = [],
    include_prefix = "eaps",
    visibility = ["//visibility:public"],
    deps = [],
)
